### ISSUE TITLE
Feedback on Project Proposal

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS/exploreR#5]
Great job! Thank you for your function descriptions. This project seems sufficient to allow for, in Tiffany's words, "making good tests, packing it up nicely, collaborating well as a team, making excellent documentation." A couple comments:
1. Will _Function 1_ output a dataframe of the number of counts of each type of variable? Or the number of unique parameters of each type of variable? Also, just to check, the outputted dataframe will be size 6x2, correct?
2. Similarly, could you please specify the dimensions of the outputted data frame? I'm sure this will become abundantly obvious to me once you start testing.
3. What type of object will the output of this function be? Several printed integers? A list? A dataframe?

**Comment by nazra-inari** [comment]
Thank you for feedback. I will try to answer your questions below.

1) Function 1 (Variable summary) will output the counts of each type of variable. For example number of Boolean variable/columns = 2 if there were 2 columns in the input dataframe. The output size will be 6x2.

2) For function 2(Missing values per variable), if the input data frame has n rows and d columns, the out data frame will be d x 2 wherein the second column will contain the count of missing values for each of the d variables.

For function 3(Dataset Size/Info) we are debating about the number of metrics we want to provide, but let say we want to provide X metrics (such as shape of the dataset, size in MB of the data set), then the output dataframe would be X by 2

3) The output will always be a dataframe. Since the function uses a dataframe as an input, we found it apt to provide the user the output in the same format.

**Comment by rachelkriggs** [comment]
A couple of corrections, and these are addressed on our Readme file
1. Function 1 will output to size 5x2.
3. Function 3 will output to size 1x3 but as Arzan mentioned this may change.

**Comment by rainerlempert** [comment]
Thank you for the updates! That all sounds fine and dandy. Best of luck!
